//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Input File Error.
		/// </summary>
		internal static string ErrMsg_Invalid_Input_File {
			get {
				return ResourceManager.GetString("ErrMsg Invalid Input File", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Current configuration exists..
		/// </summary>
		internal static string Msg_SaveAppConfig {
			get {
				return ResourceManager.GetString("Msg SaveAppConfig", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Would you like to save the current configuration?.
		/// </summary>
		internal static string Msg_SaveAppConfig_Title {
			get {
				return ResourceManager.GetString("Msg SaveAppConfig Title", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to MSysAccessStorage,MSysAccessXML,MSysACEs,MSysCompactError,MSysIMEXColumns,MSysIMEXSpecs,MSysModules,MSysModules2,MSysNavPaneGroupCategories,MSysNavPaneGroups,MSysNavPaneGroupToObjects,MSysNavPaneObjectIDs,MSysObjects,MSysQueries,MSysRelationships.
		/// </summary>
		internal static string Schema_Access_Fields {
			get {
				return ResourceManager.GetString("Schema Access Fields", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Columns.
		/// </summary>
		internal static string Schema_Columns {
			get {
				return ResourceManager.GetString("Schema Columns", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to DataTypes.
		/// </summary>
		internal static string Schema_DataTypes {
			get {
				return ResourceManager.GetString("Schema DataTypes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Indexes.
		/// </summary>
		internal static string Schema_Indexes {
			get {
				return ResourceManager.GetString("Schema Indexes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Procedures.
		/// </summary>
		internal static string Schema_Procedures {
			get {
				return ResourceManager.GetString("Schema Procedures", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to ReservedWords.
		/// </summary>
		internal static string Schema_ReservedWords {
			get {
				return ResourceManager.GetString("Schema ReservedWords", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Restrictions.
		/// </summary>
		internal static string Schema_Restrictions {
			get {
				return ResourceManager.GetString("Schema Restrictions", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Tables.
		/// </summary>
		internal static string Schema_Tables {
			get {
				return ResourceManager.GetString("Schema Tables", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Views.
		/// </summary>
		internal static string Schema_Views {
			get {
				return ResourceManager.GetString("Schema Views", resourceCulture);
			}
		}
	}
}
